version: "3.9"

services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow_training
    environment:
      - AIRFLOW_HOME=/home/airflow
    volumes:
      - ./airflow:/home/airflow        # DAGs + configs
      - ./models:/models               # KNN output
      - ./data:/data                   # Ghidra features + training input
    ports:
      - "8080:8080"  # Airflow Web UI
    command: > 
      bash -c "
      airflow standalone
      "

  tf_serving:
    image: tensorflow/serving:latest
    container_name: tf_inference
    ports:
      - "8501:8501"  # REST API
    volumes:
      - ./models:/models
    environment:
      - MODEL_NAME=my_knn_model
    command: >
      --rest_api_port=8501
      --model_name=my_knn_model
      --model_base_path=/models/my_knn_model

  tf_webui:
    image: python:3.10-slim
    container_name: tf_web_ui
    depends_on:
      - tf_serving
    volumes:
      - ./models:/models
    ports:
      - "7860:7860"  # Web UI (Gradio default)
    command: bash -c "
      pip install gradio requests &&
      python3 -u /app/web_ui.py
      "
    working_dir: /app
    volumes:
      - ./webui:/app  # Place web_ui.py here

